# fly.toml app configuration file generated for jobify-cool-hill-7784 on 2025-05-02T21:05:12+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jobify-cool-hill-7784'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
